/**
 * @file packages/catalog/src/exercises.ts
 *
 * The Grindform exercise library — an extensive, hand-curated set of
 * movements covering every muscle group, movement pattern, and common
 * piece of equipment. Seeded from (and a superset of) the movements in
 * Gargi's 8-week recomp plan, then broadened so the generator has real
 * variety to draw on for muscle-building, fat-loss, endurance, and
 * recomp goals.
 *
 * Each entry is keyed by a stable kebab-case slug. The `slug` field is
 * branded as {@link ExerciseSlug} via the `ex` builder; the catalog test
 * asserts every slug is syntactically valid and unique.
 */

import type { ExerciseSlug, Goal } from '@grindform/core';

import type { Exercise } from './types.ts';

/** Concise builder that brands the authored `slug` string. */
const ex = (e: Omit<Exercise, 'slug'> & { readonly slug: string }): Exercise => ({
  ...e,
  slug: e.slug as ExerciseSlug,
});

/** Shorthand for "suits every goal" — the most versatile staple lifts. */
const ALL: readonly Goal[] = ['build_muscle', 'lose_fat', 'build_endurance', 'recomp'];

/**
 * The full library. Ordered loosely by muscle group for readability;
 * the generator never relies on array order (it filters + scores).
 */
export const EXERCISES: readonly Exercise[] = [
  // ---------------- Glutes / posterior chain ----------------
  ex({
    slug: 'barbell-hip-thrust',
    name: 'Barbell hip thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell'],
    pattern: 'hinge',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
    cue: 'Ribs down, chin tucked, drive through heels to a full lockout.',
  }),
  ex({
    slug: 'single-leg-hip-thrust',
    name: 'Single-leg hip thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'dumbbell'],
    pattern: 'hinge',
    role: 'accessory',
    unilateral: true,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'romanian-deadlift',
    name: 'Romanian deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back'],
    equipment: ['barbell', 'dumbbell'],
    pattern: 'hinge',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
    cue: 'Soft knees, push hips back, bar stays close to the legs.',
  }),
  ex({
    slug: 'b-stance-rdl',
    name: 'B-stance RDL',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'barbell'],
    pattern: 'hinge',
    role: 'accessory',
    unilateral: true,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'conventional-deadlift',
    name: 'Conventional deadlift',
    primaryMuscles: ['hamstrings', 'glutes', 'back'],
    secondaryMuscles: ['core'],
    equipment: ['barbell'],
    pattern: 'hinge',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'kettlebell-swing',
    name: 'Kettlebell swing',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core'],
    equipment: ['kettlebell'],
    pattern: 'hinge',
    role: 'conditioning',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['lose_fat', 'build_endurance', 'recomp'],
  }),
  ex({
    slug: 'cable-pull-through',
    name: 'Cable pull-through',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['cable'],
    pattern: 'hinge',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'hip-abduction',
    name: 'Hip abduction (machine or band)',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    equipment: ['machine', 'band'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),

  // ---------------- Quads ----------------
  ex({
    slug: 'back-squat',
    name: 'Back squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['barbell'],
    pattern: 'squat',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
    cue: 'Brace, break at hips and knees together, drive the floor away.',
  }),
  ex({
    slug: 'front-squat',
    name: 'Front squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['barbell'],
    pattern: 'squat',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'goblet-squat',
    name: 'Goblet squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbell', 'kettlebell'],
    pattern: 'squat',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian split squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    pattern: 'lunge',
    role: 'accessory',
    unilateral: true,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'walking-lunge',
    name: 'Walking lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    pattern: 'lunge',
    role: 'accessory',
    unilateral: true,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'leg-press',
    name: 'Leg press',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    pattern: 'squat',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'dumbbell-step-up',
    name: 'DB step-up',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    pattern: 'lunge',
    role: 'accessory',
    unilateral: true,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'leg-extension',
    name: 'Leg extension',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp'],
  }),

  // ---------------- Hamstrings ----------------
  ex({
    slug: 'seated-leg-curl',
    name: 'Seated leg curl',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['machine'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'lying-leg-curl',
    name: 'Lying leg curl',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: ['machine'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'nordic-curl',
    name: 'Nordic hamstring curl',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'advanced',
    goals: ['build_muscle', 'recomp'],
  }),

  // ---------------- Calves ----------------
  ex({
    slug: 'standing-calf-raise',
    name: 'Standing calf raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine', 'dumbbell', 'bodyweight'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'seated-calf-raise',
    name: 'Seated calf raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp'],
  }),

  // ---------------- Back ----------------
  ex({
    slug: 'lat-pulldown',
    name: 'Lat pulldown',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable', 'machine'],
    pattern: 'vertical_pull',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'pull-up',
    name: 'Pull-up / assisted',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['bodyweight', 'machine'],
    pattern: 'vertical_pull',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'barbell-row',
    name: 'Barbell row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['barbell'],
    pattern: 'horizontal_pull',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'seated-cable-row',
    name: 'Seated cable row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable', 'machine'],
    pattern: 'horizontal_pull',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'chest-supported-db-row',
    name: 'Chest-supported DB row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    pattern: 'horizontal_pull',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'single-arm-db-row',
    name: 'Single-arm DB row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    pattern: 'horizontal_pull',
    role: 'accessory',
    unilateral: true,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'face-pull',
    name: 'Face pull',
    primaryMuscles: ['back', 'shoulders'],
    secondaryMuscles: [],
    equipment: ['cable', 'band'],
    pattern: 'horizontal_pull',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),

  // ---------------- Chest ----------------
  ex({
    slug: 'barbell-bench-press',
    name: 'Barbell bench press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell'],
    pattern: 'horizontal_push',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'incline-barbell-bench',
    name: 'Incline BB bench',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell'],
    pattern: 'horizontal_push',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'incline-db-press',
    name: 'Incline DB press',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    pattern: 'horizontal_push',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'flat-db-press',
    name: 'DB flat bench press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell'],
    pattern: 'horizontal_push',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'push-up',
    name: 'Push-up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: ['bodyweight'],
    pattern: 'horizontal_push',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'cable-fly',
    name: 'Cable fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: ['cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'cable-crossover',
    name: 'Cable crossover',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: ['cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),

  // ---------------- Shoulders ----------------
  ex({
    slug: 'overhead-press',
    name: 'Overhead press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell'],
    pattern: 'vertical_push',
    role: 'main',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'db-shoulder-press',
    name: 'DB shoulder press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    pattern: 'vertical_push',
    role: 'main',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'lateral-raise',
    name: 'Lateral raise',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'rear-delt-fly',
    name: 'Rear delt fly',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['dumbbell', 'cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),

  // ---------------- Biceps ----------------
  ex({
    slug: 'dumbbell-curl',
    name: 'Dumbbell curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'hammer-curl',
    name: 'Hammer curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'incline-db-curl',
    name: 'Incline DB curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'cable-curl',
    name: 'Cable curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),

  // ---------------- Triceps ----------------
  ex({
    slug: 'tricep-pushdown',
    name: 'Tricep pushdown',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'skull-crusher',
    name: 'Skull crusher (EZ)',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['barbell', 'dumbbell'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'overhead-tricep-extension',
    name: 'Overhead tricep extension',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'cable'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'bench-dip',
    name: 'Bench dip',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['bodyweight'],
    pattern: 'isolation',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),

  // ---------------- Core ----------------
  ex({
    slug: 'plank',
    name: 'Plank',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'core',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'hanging-knee-raise',
    name: 'Hanging knee raise',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'core',
    role: 'accessory',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['build_muscle', 'recomp', 'build_endurance'],
  }),
  ex({
    slug: 'cable-crunch',
    name: 'Cable crunch',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['cable'],
    pattern: 'core',
    role: 'accessory',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['build_muscle', 'recomp'],
  }),
  ex({
    slug: 'pallof-press',
    name: 'Pallof press',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['cable', 'band'],
    pattern: 'core',
    role: 'accessory',
    unilateral: true,
    minExperience: 'beginner',
    goals: ALL,
  }),
  ex({
    slug: 'dead-bug',
    name: 'Dead bug',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'core',
    role: 'mobility',
    unilateral: false,
    minExperience: 'beginner',
    goals: ALL,
  }),

  // ---------------- Full body / conditioning ----------------
  ex({
    slug: 'dumbbell-thruster',
    name: 'Dumbbell thruster',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['quads', 'shoulders'],
    equipment: ['dumbbell', 'kettlebell'],
    pattern: 'conditioning',
    role: 'conditioning',
    unilateral: false,
    minExperience: 'intermediate',
    goals: ['lose_fat', 'build_endurance'],
  }),
  ex({
    slug: 'burpee',
    name: 'Burpee',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['chest', 'quads'],
    equipment: ['bodyweight'],
    pattern: 'conditioning',
    role: 'conditioning',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['lose_fat', 'build_endurance'],
  }),
  ex({
    slug: 'rowing-intervals',
    name: 'Rowing intervals',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['back', 'quads'],
    equipment: ['machine'],
    pattern: 'conditioning',
    role: 'conditioning',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['lose_fat', 'build_endurance', 'recomp'],
  }),
  ex({
    slug: 'farmer-carry',
    name: 'Farmer carry',
    primaryMuscles: ['full_body', 'core'],
    secondaryMuscles: ['back'],
    equipment: ['dumbbell', 'kettlebell'],
    pattern: 'carry',
    role: 'conditioning',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['lose_fat', 'build_endurance', 'recomp'],
  }),
  ex({
    slug: 'mountain-climber',
    name: 'Mountain climber',
    primaryMuscles: ['full_body', 'core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'conditioning',
    role: 'conditioning',
    unilateral: false,
    minExperience: 'beginner',
    goals: ['lose_fat', 'build_endurance'],
  }),
];
